#!/bin/sh

projects=$(bloop projects)
current_project=$(echo "$projects" | head -n1)

test=false
only=false
flags=" "

while test $# != 0
do
  case "$1" in
    -o|--only) only=true;;
    -t|--test) test=true;;
    -noi) flags="$flags --incremental=false ";;
    -w) flags="$flags --watch ";
  esac
  shift
done;


if [ "$only" = true ]; then
  class_file=$(find . -name '*Test.scala' | fzf)
  package=$(grep '^package ' $class_file | sed 's/package //')
  class_name=$(echo $class_file | sed 's/.*\/\(.*\)\.scala/\1/')
  class="$package.$class_name"

  flags="$flags --only $class "
fi


if [ "$test" = true ]; then
  bloop test $current_project $flags
else
  bloop compile $current_project $flags
fi

