#!/bin/sh

projects=$(bloop projects)
current_project=$(echo "$projects" | head -n1)

run=false
test=false
only=false
copy=false
flags=" "

while test $# != 0
do
  case "$1" in
    -o|--only) only=true; test=true ;;
    -t|--test) test=true ;;
    -r|--run) run=true ;;
    -n) flags="$flags --incremental=false " ;;
    -w) flags="$flags --watch " ;;
    -c) copy=true ;;
    *)  echo "Unrecognized flag: $1" ;;
  esac
  shift
done


if [ "$only" = true ]; then
  class_file=$(find . -name '*Test.scala' | fzf)
  package=$(grep '^package ' $class_file | sed 's/package //')
  class_name=$(echo $class_file | sed 's/.*\/\(.*\)\.scala/\1/')
  class="$package.$class_name"

  flags="$flags --only $class "
fi

command=""
if [ "$test" = true ]; then
  command="bloop test $current_project $flags"
elif [ "$run" = true ]; then
  command="bloop run $current_project $flags"
else
  command="bloop compile $current_project $flags"
fi

if [ "$copy" = true ]; then
  echo "$command" | xclip -selection clipboard
  echo "Command copied to clipboard!"
else
  eval "$command"
fi
