#!/bin/bash

reinitialize_git=false

while test $# != 0
do
  case "$1" in
    -g|--git) reinitialize_git=true;;
    *)  echo "Unrecognized flag: $1" ;;
  esac
  shift
done

# remove scala project files
rm -rf project/project project/target target project/.bloop

# remove protobuf files
rm -rf *protobufs

# remove bloop / metals / bsp
rm -rf .bloop .metals .bsp project/metals.sbt

if [ "$reinitialize_git" = true ]; then
  # remove old git repository
  rm -rf .git .gitmodules

  # initialize a fresh git repository
  git init
fi
