#!/bin/bash

url="https://www.worldometers.info/coronavirus/"

corona_file=$(mktemp "corona-XXX")

curl -s "$url" > "$corona_file"

count=$(cat "$corona_file" | pup 'table[id="main_table_countries_today"] tbody tr:parent-of(td:parent-of(a:contains("Poland"))) td:nth-child(2) text{}')
increase=$(cat "$corona_file" | pup 'table[id="main_table_countries_today"] tbody tr:parent-of(td:parent-of(a:contains("Poland"))) td:nth-child(3) text{}')

rm "$corona_file"

echo "😷 $count ($increase)"
