#!/bin/bash

API_URL="https://gitlab.com/api/v4"
TOKEN="CWs4zZpQvf5aUos897jg"
QUERY="private_token=$TOKEN&membership=true&per_page=100"
URL="$API_URL/projects?$QUERY"
CACHE_PATH="$HOME/.glclone-cache"


if [ -f $CACHE_PATH ] && [ "$1" != "-r" ]; then
    CHOSEN_URL=`cat $CACHE_PATH | sed 's/ /\n/g' | fzf`
else
    SSH_REPO_URLS=`curl --silent $URL | jq '.[] | .ssh_url_to_repo' | sed 's/"//g'`
    echo $SSH_REPO_URLS > $CACHE_PATH
    CHOSEN_URL=`cat $CACHE_PATH | sed 's/ /\n/g' | fzf`
fi

git clone $CHOSEN_URL --recursive
