#!/bin/bash


choice=$(printf "A2DP\nHandsfree Head Unit" | rofi -dmenu)


case "$choice" in
    "A2DP") pacmd set-card-profile 20 a2dp_sink ;;
    "Handsfree Head Unit") pacmd set-card-profile 20 handsfree_head_unit ;;
    *)  # ignore
esac

