#!/bin/bash

dir="$1"
index_file="/home/porcupine/.local/share/z/data"
timestamp=$(date +"%s" )

declare -a root_files=(
    "requirements.txt"
    "build.sbt"
)

for i in ${!root_files[@]};
do
  fname=${root_files[$i]}
  for f in $(find "$dir" | grep "$fname");
  do
      fdir=${f%/"$fname"}
      if ! grep -q "^$fdir|" "$index_file"; then
        echo "$fdir|1|$timestamp" >> "$index_file"
      fi
  done 
done
