#!/bin/bash

set -e

master="lkazmierczak@192.168.0.11"

if [ $# -lt 2 ]; then
    echo "Usage: STACK QUERY ARGS"
else
    stack="$1"; shift
    query="$1"; shift
    args="$@"

    output=$(ssh "$master" sudo docker stack ps "$stack" | grep "Running" | grep "$query")
    choice=$(echo "$output" | fzf)
    node_id=$(echo "$choice" | sed "s/\\\_//" | awk '{ print $4 }')

    node_ip=$(ssh "$master" "sudo docker node inspect --format '{{ .Status.Addr }}' $node_id")
    node="lkazmierczak@$node_ip"

    output=$(ssh "$node" sudo docker ps | grep "$stack" | grep "$query")
    choice=$(echo "$output" | fzf)
    container_id=$(echo "$choice" | cut -d' ' -f1)

    ssh "$node" sudo docker logs --follow "$container_id" $args 2>&1
fi

