#!/bin/bash

program="$1"
throttle=0.3

{
while true; do
    start=`date +%s%N`

    eval "$program"

    end=`date +%s%N`

    runtime=$(((end-start)/1000000))

    echo "$runtime"

    sleep "$throttle"
done
} | ttyplot
