#!/usr/bin/env python

import subprocess
import argparse
import sched, time

scheduler = sched.scheduler(time.time, time.sleep)

parser = argparse.ArgumentParser(description="Tmuxinator debuger.")
parser.add_argument("-a", "--at", type=str)

def send_notification():
    subprocess.run(["notify-send", "hello"])

scheduler.enter(10, 1, send_notification)
scheduler.run()
