#!/bin/bash

env="sl-dev-main-ll"
if [ $# = 1 ]; then
   env="$1"
fi   


function choose_dev {
    choices=$(kubectl get namespaces --context zowie-dev-k8s | grep sl-dev | cut -d' ' -f1)
    dev=$(printf "%s\n" "${choices[@]}" | fzf)
    return dev
}

declare -a options=(
  "ai-project-service"
  "ai-import-service"
  "creator-automation-statistics-service"
  "creator-phrase-query-service"
  "crm-service"
  "inbox-search-service"
  "inbox-integration-product-feed-service"
)

#choose_dev

db=$(printf "%s\n" "${options[@]}" | fzf)


PGPASSWORD="$env" pgcli -U "$env-app" -h \
  zowie-dev-psql1.cluster-c4mxgrjdwroj.eu-west-1.rds.amazonaws.com \
  -p 5432 -d "$env-$db"
