#!/usr/bin/env python3

import json
import subprocess

from time import sleep

SPACE_TARGET = 10

displays = json.loads(subprocess.check_output(["yabai", "-m", "query", "--displays"]))
spaces = json.loads(subprocess.check_output(["yabai", "-m", "query", "--spaces"]))

current_display = {str(s["index"]): str(s["display"]) for s in spaces}

print(current_display)

# format: off
layout_3 = {
    "1": ["1", "2", "3", "4"],
    "2": ["8", "9", "10"],
    "3": ["5", "6", "7"],
}
# format: on

if len(displays) == 3:
    for tg_d, tg_s in layout_3.items():
        for spc in tg_s:
            c_d = current_display[spc]
            if c_d != tg_d:
                print(f"Moving {spc} from {c_d} to {tg_d}")
                subprocess.check_output(
                    ["yabai", "-m", "space", spc, "--display", tg_d]
                )
                sleep(0.25)

for i in range(SPACE_TARGET - len(spaces)):
    subprocess.check_output(["yabai", "-m", "space", "--create"])

for s in current_display:
    if int(s) > SPACE_TARGET:
        subprocess.check_output(["yabai", "-m", "space", s, "--destroy"])
        sleep(0.25)



subprocess.check_output(["sketchybar", "--reload"])

#yabai --restart-service
