#!/bin/bash

cheatsheet_dir="$HOME/Dropbox/org/resources/cheatsheets/"

choice=$(ls $cheatsheet_dir | rofi -i -dmenu -dpi 196 -show-icons -font "Fira Mono 11")

if [[ ! -z "$choice" ]]; then
    zathura "$cheatsheet_dir$choice"
fi
