#!/bin/bash


declare -a options=(
  "Monorepo Pull Requests"
  "Chatbotize Jenkins"
  "Admin Test Account"
  "Jira Chatbotize Dev" 
  "Jira Chatbotize SUP" 
  "Weather"
  "Knowledge Base"
  "Home Assistant"
)


function to_url() {
  case "$1" in
    "Monorepo Pull Requests")   echo "https://github.com/chatbotizeteam/monorepo/pulls" ;;
    "Chatbotize Jenkins")       echo "https://jenkins.codeheroes.tech/blue/organizations/jenkins/monorepo/activity" ;;
    "Admin Test Account")       echo "https://admin.vpn.zowie.ai/environments/aa23bb62336f43bf84710b834217564d" ;;
    "Jira Chatbotize Dev")      echo "https://chatbotize.atlassian.net/jira/software/projects/CD/boards/1" ;;
    "Jira Chatbotize SUP")      echo "https://chatbotize.atlassian.net/jira/servicedesk/projects/SUP/queues/custom" ;;
    "Weather")                  echo "https://m.meteo.pl/krakow/60" ;;
    "Knowledge Base")           echo "/home/porcupine/kb/index.html" ;;
    "Home Assistant")           echo "http://192.168.1.29:8123/" ;;
  esac
}


choice=$(printf "%s\n" "${options[@]}" | selector)

if [[ -n "$choice" ]]; then
  url=$(to_url "$choice")

  bash -c "xdg-open $url; (true)" >> /dev/null 2>&1
fi
