#!/bin/bash


declare -a options=(
  "Chatbotize Stage"
  "Chatbotize Dev"
  "Herochat Stage (Private)"
  "Monorepo Pull Requests"
  "Chatbotize Jenkins"
  "Jira Chatbotize Dev"
  "Jira Chatbotize FF"
  "GitLab Activity"
)


function to_url() {
  case "$1" in
    "Chatbotize Stage")         echo "https://core-chatbotize.stage.codeheroes.tech" ;;
    "Chatbotize Dev")           echo "https://core-chatbotize.dev.codeheroes.tech" ;;
    "Herochat Stage (Private)") echo "--incognito https://at-herochat.test.codeheroes.tech/384fc79042264756bb76f0412a8d812e" ;;
    "Monorepo Pull Requests")   echo "https://github.com/chatbotizeteam/monorepo/pulls" ;;
    "Chatbotize Jenkins")       echo "https://jenkins.codeheroes.tech/blue/organizations/jenkins/monorepo/activity" ;;
    "GitLab Activity")          echo "https://gitlab.com/dashboard/activity" ;;
    "Jira Chatbotize Dev")      echo "https://chatbotize.atlassian.net/jira/software/projects/CD/boards/1" ;;
    "Jira Chatbotize FF")       echo "https://chatbotize.atlassian.net/jira/servicedesk/projects/FF/queues/custom/25" ;;
  esac
}


choice=$(printf "%s\n" "${options[@]}" | rofi -i -dmenu -dpi 196 -show-icons -font "Fira Mono 11")

if [[ ! -z "$choice" ]]; then
  url=$(to_url "$choice")

  bash -c "brave-browser $url; (true)" >> /dev/null 2>&1
fi
