#!/bin/bash

path="$HOME/Dropbox/org/resources/papers"


list() {
    choice=$(ls "$1" | selector)

    if [[ ! -z "$choice" ]]; then
        case $(stat -c "%F" "$1/$choice") in
            directory) list "$1/$choice" ;;
            *) zathura "$1/$choice" ;;
        esac
    fi
}


list "$path"
