#!/bin/bash

primary_display="eDP-1"
display_count=$(xrandr | grep -i ' connected' | wc -l)

case $display_count in
    1)
	i3-msg '[class="kitty"] move to workspace number 1' 
	i3-msg '[class="firefox"] move to workspace number 2'
	i3-msg '[class="Emacs"] move to workspace number 3'
	i3-msg '[class="Ferdium"] move to workspace number 4'
	i3-msg '[class="Spotify"] move to workspace number 5'
	restart_polybar
	;;
    2)
	snd_display=$(xrandr | grep -i ' connected' | cut -d' ' -f1 | grep -v "$primary_display")

	i3-msg '[class="kitty"] move to workspace number 1' 
        i3-msg "workspace number 1; move workspace to output $snd_display"
	i3-msg '[class="firefox"] move to workspace number 2'
        i3-msg "workspace number 2; move workspace to output $snd_display"
	i3-msg '[class="Emacs"] move to workspace number 3'
        i3-msg "workspace number 3; move workspace to output $snd_display"
        i3-msg "workspace number 8; move workspace to output $snd_display"
	i3-msg '[class="Ferdium"] move to workspace number 4'
	i3-msg '[class="Spotify"] move to workspace number 4'
        i3-msg "workspace number 4; move workspace to output $primary_display"
	restart_polybar
	;;
    3)
        if xrandr | grep -i ' connected' | grep -q 'HDMI'; then
	    snd_display="HDMI-1"
	    trd_display="DP-2"
	else
	    snd_display="DVI-I-1-1"
	    trd_display="DVI-I-2-2"
	fi

	i3-msg '[class="kitty"] move to workspace number 1' 
        i3-msg "workspace number 1; move workspace to output $snd_display"
	i3-msg '[class="firefox"] move to workspace number 2'
        i3-msg "workspace number 2; move workspace to output $snd_display"
	i3-msg '[class="Emacs"] move to workspace number 3'
        i3-msg "workspace number 3; move workspace to output $snd_display"
        i3-msg "workspace number 8; move workspace to output $snd_display"
	i3-msg '[class="Ferdium"] move to workspace number 4'
        i3-msg "workspace number 4; move workspace to output $trd_display"
	i3-msg '[class="Spotify"] move to workspace number 5'
        i3-msg "workspace number 5; move workspace to output $primary_display"
	restart_polybar
	;;
    *)
	exit 1
	;;
esac
