#!/bin/bash

HOST=$(grep "Host " ~/.ssh/config | sed "s/Host //" | fzf)

if [[ -z $HOST ]]; then
    exit
fi

TO_FORWARD=$(echo -e "none\nmongo\npostgres\ncassandra\nkafka" | fzf)

if [[ -z $TO_FORWARD ]]; then
    exit
fi

declare -A PORTS=(
    ["mongo"]="27017"
    ["postgres"]="5432"
    ["cassandra"]="9042"
    ["kafka"]="9092"
)

if [[ "$TO_FORWARD" == "none" ]]; then
    ssh $HOST
else
    PORT="${PORTS["$TO_FORWARD"]}"
    DOCKER_PS=$(ssh $HOST "sudo docker ps")
    INTERNAL_IP=$(echo "$DOCKER_PS" | grep "$TO_FORWARD" | sd '.*?((?:\d+\.){3}\d+).*' '$1' | head -n1 | sd "\s+" "")
    ssh -L "$PORT:$INTERNAL_IP:$PORT" $HOST
fi
