#!/bin/bash

url="http://home.agh.edu.pl/~darbski/"

http --check-status --output none $url

status=$?

while [[ 1 == 1 ]]; do

    if [[ $status == 0 ]]; then
        notify-send -u critical "|---- SJO ----|"
    fi;

    sleep 1

done;
