#!/bin/bash

script="/home/porcupine/.pyenv/versions/idasen/bin/idasen-controller"

if [ $# = 1 ]; then
    choice="$1"
else
    declare -a options=(
	"stand"
	"sit"
	"eat"
    )

    choice=$(printf "%s\n" "${options[@]}" | rofi -dmenu)
fi

case "$choice" in 
    "stand") eval "$script --stand" ;;
    "sit") eval "$script --move-to 675" ;;
    "eat") eval "$script --move-to 850" ;;
esac
