#!/bin/bash

export EDITOR="nvim"
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=qt6ct
export QT_AUTO_SCREEN_SCALE_FACTOR=0 
export GTK_USE_PORTAL=0
export ANKI_WAYLAND=1

export GLFW_IM_MODULE='ibus'
export GTK_IM_MODULE='fcitx'
export QT_IM_MODULE='fcitx'
export SDL_IM_MODULE='fcitx'
export XMODIFIERS='@im=fcitx'

# eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
# export $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)
# systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP SWAYSOCK
# dbus-update-activation-environment --systemd DISPLAY

eval $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh) || echo "gnome-keyring-daemon not found or failed"
export SSH_AUTH_SOCK

dropbox &
copyq &
dunst &
fcitx5 &

if command -v nixGLIntel >/dev/null; then
	exec nixGLIntel Hyprland
else
	exec Hyprland
fi
