#!/bin/bash

set -e

if [[ "$#" != 3 ]]; then
  echo "Usage: dict_file key target_file"
  exit 1
fi

dict_file="$1"
key="$2"
target_file="$3"

matches=($(grep "$key" "$target_file" | sd "$key"': (.*) *' '$1' | tr -d '"'))
uniq_matches=($(echo "${matches[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))

jq -c '.[]' "$dict_file" | while read i; do
    id=$(echo "$i" | jq ".$key" | tr -d '"')
    name=$(echo "$i" | jq ".name" | tr -d '"')

    if [[ " ${uniq_matches[@]} " =~ " $id " ]]; then 
	sd "(?P<before>\"?$key\"?.*)($id)(?P<after>.*)" '${before}'"$name"'${after}' "$target_file"
    fi
done
