#!/bin/bash

if [[ "$#" != 1 ]]; then
    echo "Usage: update-metals [version]"
else
    ~/tool/coursier bootstrap \
        --java-opt -Xss4m \
        --java-opt -Xms100m \
        --java-opt -Dmetals.client=emacs \
        org.scalameta:metals_2.12:"$1" \
        -r bintray:scalacenter/releases \
        -r sonatype:snapshots \
        -o /usr/local/bin/metals-emacs -f

    echo "$1" > ~/.cache/update-metals/version
fi
