#!/bin/bash

default_sink=$(pactl info | grep 'Default Sink' | sed -E 's/Default Sink: (.*)/\1/')

case "$1" in
    "toggle") pactl set-sink-mute $default_sink toggle ;;
    "up") pactl set-sink-volume $default_sink +2% ;;
    "down") pactl set-sink-volume $default_sink -2% ;;
esac
