#!/bin/bash

case "$1" in
    "toggle") pactl set-sink-mute @DEFAULT_SINK@ toggle ;;
    "up") pactl set-sink-volume @DEFAULT_SINK@ +2% ;;
    "down") pactl set-sink-volume @DEFAULT_SINK@ -2% ;;
esac

# get default sink volume
# SINK=$(pactl list short sinks | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,' | head -n 1 )
# VOLUME=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')

# # set all "subsinks" (applications) to the same value
# for i in $(pactl list sink-inputs | grep 'Sink Input #' | awk '{print $3}' | tr -d '#'); do
#     pactl set-sink-input-volume "$i" "$VOLUME%"
# done 
